# Generated by Django 6.0.4 on 2026-08-04 08:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_per_credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.05'), help_text='Contoh: 0.05 = 5%', max_digits=5)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10)),
                ('status', models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished')], default='unpublished', max_length=15)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marketplace_listings',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_issued', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('available', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sold', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reserved', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('retired', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('buffer', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('listing', models.OneToOneField(db_column='listing_id', on_delete=django.db.models.deletion.CASCADE, related_name='credit_inventory', to='projects.marketplacelisting')),
            ],
            options={
                'verbose_name_plural': 'Credit Inventories',
                'db_table': 'credit_inventory',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('forestry', 'Forestry & Land Use'), ('renewable_energy', 'Renewable Energy'), ('agriculture', 'Agriculture'), ('waste_management', 'Waste Management'), ('blue_carbon', 'Blue Carbon'), ('energy_efficiency', 'Energy Efficiency'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('methodology', models.CharField(max_length=255)),
                ('registry', models.CharField(blank=True, choices=[('verra', 'Verra (VCS)'), ('gold_standard', 'Gold Standard'), ('acr', 'American Carbon Registry (ACR)'), ('car', 'Climate Action Reserve (CAR)'), ('plan_vivo', 'Plan Vivo'), ('other', 'Other')], max_length=50)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20)),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, help_text='Luas area proyek (hektar).', max_digits=15, null=True)),
                ('deforestation_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Tingkat deforestasi historis baseline (%).', max_digits=6, null=True)),
                ('expected_credits', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('vintage_year', models.PositiveIntegerField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_range', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='project',
            field=models.OneToOneField(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listing', to='projects.project'),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('pdd', 'Project Design Document (PDD)'), ('validation_report', 'Validation Report'), ('monitoring_report', 'Monitoring Report'), ('verification_report', 'Verification Report'), ('legal_document', 'Legal Document'), ('other', 'Other')], max_length=50)),
                ('file_url', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'db_table': 'project_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='projects.project')),
            ],
            options={
                'db_table': 'project_faqs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImpact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impact_type', models.CharField(choices=[('trees', 'Pohon Ditanam'), ('species', 'Spesies Dilindungi'), ('people', 'Masyarakat Terbantu'), ('other', 'Lainnya')], max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Emoji, misal 🌲', max_length=10)),
                ('label', models.CharField(help_text="Teks tampil, misal '250.000+ Ditanam'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='projects.project')),
            ],
            options={
                'db_table': 'project_impacts',
                'ordering': ['order'],
            },
        ),
    ]
