# Generated by Django 6.0.7 on 2026-07-23 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area_hectares',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Luas area proyek (hektar).', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deforestation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tingkat deforestasi historis baseline (%).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='serial_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='verified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='vintage_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='project',
            field=models.OneToOneField(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listing', to='projects.project'),
        ),
    ]
