# Generated by Django 6.0.7 on 2026-07-23 06:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_area_hectares_project_deforestation_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='platform_fee_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.05'), help_text='Contoh: 0.05 = 5%', max_digits=5),
        ),
        migrations.CreateModel(
            name='ProjectFAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='projects.project')),
            ],
            options={
                'db_table': 'project_faqs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImpact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impact_type', models.CharField(choices=[('trees', 'Pohon Ditanam'), ('species', 'Spesies Dilindungi'), ('people', 'Masyarakat Terbantu'), ('other', 'Lainnya')], max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Emoji, misal 🌲', max_length=10)),
                ('label', models.CharField(help_text="Teks tampil, misal '250.000+ Ditanam'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='projects.project')),
            ],
            options={
                'db_table': 'project_impacts',
                'ordering': ['order'],
            },
        ),
    ]
