# Generated by Django 6.0.7 on 2026-08-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_marketplacelisting_platform_fee_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area_geojson',
            field=models.JSONField(blank=True, help_text='Polygon/MultiPolygon lokasi proyek dalam format GeoJSON, dipakai untuk query GFW API.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deforestation_checked_at',
            field=models.DateTimeField(blank=True, help_text='Kapan terakhir kali data deforestasi diambil dari GFW API.', null=True),
        ),
    ]
