# Generated by Django 6.0.4 on 2026-08-04 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tree_count', models.IntegerField()),
                ('average_dbh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('root_to_shoot_ratio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('soil_organic_carbon', models.DecimalField(decimal_places=2, max_digits=15)),
                ('above_ground_biomass', models.DecimalField(decimal_places=2, max_digits=15)),
                ('below_ground_biomass', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_gross_carbon_stock', models.DecimalField(decimal_places=2, max_digits=15)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('issuable_credits', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('verified', 'Verified')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='mrv_records', to='projects.project')),
            ],
            options={
                'verbose_name': 'MRV',
                'verbose_name_plural': 'MRV Records',
                'db_table': 'mrv',
                'ordering': ['-created_at'],
            },
        ),
    ]
