# Generated by Django 6.0.4 on 2026-08-04 08:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_per_credit', models.DecimalField(decimal_places=2, help_text='Snapshot harga per kredit saat transaksi dibuat.', max_digits=15)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('card', 'Kartu Kredit / Debit'), ('bank_transfer', 'Bank Transfer / Invoice ESG')], default='card', max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=15)),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('certificate_url', models.TextField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(db_column='listing_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='projects.marketplacelisting')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
